### ISSUE TITLE
Uniciv issue

### ISSUE THREAD

**Issue by dgishere** [NoviceCoder2000/Wars-Mod#1]
![Screenshot_20220318_000212](https://user-images.githubusercontent.com/101818758/158842289-9bc408b5-79b5-489d-92db-22fd64be4272.jpg)

Hey there. Can you please make some fix in this problem. I really wanted to play this mod so much.

**Comment by NoviceCoder2000** [comment]
Hi there! Sorry for the very long reply but are you by any chance playing in a different ruleset?

**Comment by dgishere** [comment]
Oh now I can play the mod. Thanks a lot and sorry if my reply take so long
